[theme]
primaryColor = "#4CAF50"  # Your custom primary color
backgroundColor = "#FFFFFF"  # Background color
secondaryBackgroundColor = "#F0F2F6"  # Sidebar background
textColor = "#000000"  # Text color
font = "sans serif"  # Available options: 'sans serif', 'serif', or 'monospace'
